# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70b9d84e93d578b5b4090893b002bea641db068615e9cdea88d96d48b7b17cadea59c74376cc62c7d74ab305061caad94bc30b10436a632e8f732c8005083194

test:
  secret_key_base: 8ab69e1710fe5ca2951f983425c7e0b89eb8f2df582591ef05f9c077947427133bba8bfa05cf14c1cfd2e9db6968fce6fff10eaa31ef419b837373a774d37c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
